### ISSUE TITLE
Make the Admin leaderboards more informative

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#141]
The admin leaderboards don't show information about the MCW dataset nor the name of the tool.

Suggestion: Mirror the content of the "production" leaderboard to the admin leaderboard.

**Comment by thomasyu888** [comment]
@tschaffter I actually recommend looking at the submission views instead of using these admin pages: 

* Admin view: https://www.synapse.org/#!Synapse:syn23633030/tables/
* View that shows all the test queues: https://www.synapse.org/#!Synapse:syn23512270/tables/
* Leaderboard view: https://www.synapse.org/#!Synapse:syn23747126/tables/

**Comment by tschaffter** [comment]
I like this @thomasyu888 ! This will contribute to declutter the admin section of the wiki. Can you open a PR?

**Comment by thomasyu888** [comment]
@tschaffter Did you want me to delete all the admin leaderboard pages and just add one page

**Comment by tschaffter** [comment]
@thomasyu888 Yes
