### ISSUE TITLE
Review submission sharing (license, rules, protocol)

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#45]
The current Rules state that the [submissions must not contain proprietary content and that the submissions will be released under an open source license](https://github.com/nlpsandbox/nlpsandbox-website-synapse/blame/staging/wiki/604831-Rules.md#L19-L26). 

Comments:

- @ychae Does this rule come from the DREAM Challenge rules? Often challenge participants can choose after the end of the challenge whether they don't want us (Organizers) to release their model, in which case they become no longer eligible for incentives (cash prize, manuscript authorship).
- Usually the release of models applies at the end of the challenge. The NLP Sandbox is a continuous benchmarking project without planned end date.

Questions:

- Are we releasing the submission? I.e. do we enforce the release by creating an archive of the submission publicly accessible as we did at the end of the DM Challenge?
- If we control the release, when do we release the submission? Right after a successful evaluation? Weekly? Monthly?
- Or do we let the submitters choose whenever they want to release their submission?
- If we request the submission to be released publicly, we could use the value of the property `license` that submitters are required to specify as part of their submission to decide whether the license is "open" and whether we move on with the evaluation of the submission. I.e. submissions with a license that we do not consider "open" (to identify from our [License schema](https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/components/parameters/License.yaml)) would be rejected.

Notes:

- The developers must specify the license of their tool (returned by `/api/v1/tool` or `/`). We could use this value to perform a conditional action like creating an archived version of the submission and release it publicly. This will ensure that the submission will always be publicly available. Or we let the submitter full control over the sharing settings of their submission. This gives them more flexibility, but there is a chance that they will overlook this extra step (i.e. changing the permission settings) which will results in less NLP tools being publicly accessible.

- We are providing the NLP Sandbox as a free service and our organization (Sage) promotes open science. It would be legitimate for us to request submitters to agree to release their method under an open source license.

- However, our goal is also to capture the performance of as many tools as possible in order to depict an accurate picture of the state of the art in terms of method performance. Forcing submitters to agree to release their methods under an open source license may prevent companies with performant but proprietary solutions to submit their method for evaluation in the first place. If we capture the existence of those methods, interested parties can reach out to the submitters to negotiate access to the methods.

Preferred approach?

The easiest solution for us is to let the submitters control the sharing of their submissions. Also if we create archives of the submitted docker image, I expect that we would not give them a nice name due to the way Synapse names docker images.

That said, I'm interested in displaying the license specified by the submitter in the leaderboard table. We can get this value from `/` or `/api/v1/tools` as mentioned previously. If there is a benefit, we could also ask the developer to specify this information as a Docker LABEL (the value of the license could be retrieved without running the container).

**Comment by allaway** [comment]
I have a few thoughts regarding the broader question that you posed on slack:

>What should be Sage/DREAM/other common SOP regarding the release of models submitted to challenges?

Context probably matters here. What is the goal? With DREAM challenges, the goal seems often to spur innovation in a specific *under served* problem area, release those models to the public to facilitate future development (hence the rule you highlighted above), and reward the people who produce the top methods with cash, paper writing opportunity, presentation platform, etc. In this case, it makes sense that an open license is a mandate, because it's trying to lay a foundation for the field.

With the continuous benchmarking challenges - the predominant goal seems (to me) to try and provide an independent benchmark of methods typically in a more *well-developed* field (like the example you outlined - a field mature enough where folks are trying to commercialize models). As you note, you probably want to be able to benchmark proprietary non-open methods as well to accurately assess both how the field as a whole is doing, as well as whether any individual company or method can actually do what it claims. In this case, I think the goal is to solve the type of controversy that occurs around methods [like this](https://www.nature.com/articles/s41586-019-1799-6) where a company swoops in with a method, but their claims cannot be independently assessed because they won't publicized the code "The code used for training the models has a large number of dependencies on internal tooling, infrastructure and hardware, and its release is therefore not feasible." More reading on this here: https://www.nature.com/articles/s41586-020-2766-y

Anyway - my take is that there is probably not a good SOP that applies to all of these different benchmarking use cases. I think one has to define what the landscape of goals are first and develop a system that can fulfill these various use cases. DREAM challenges probably *should* enforce selection of a license at the time of submission, and notify the submitter that they have x number of days (until the conclusion of the challenge) to withdraw their model if they don't want it released under these conditions. Conversely, the "well developed field benchmarking" type challenge might want to enforce openness, or it might want to simply facilitate submission of both open and closed models for benchmarking. In this scenario, the submission could be listed as open or proprietary at the time of submission.

In either case, I think these should be defined at the time of submission, not later, because, as you note, it's unlikely that you'll capture this information down the road. 


> If we control the release, when do we release the submission? Right after a successful evaluation? Weekly? Monthly? 
> Or do we let the submitters choose whenever they want to release their submission?

Perhaps this can be defined on a project by project basis? 

edit: adding CC0 license to this comment 🙃

**Comment by tschaffter** [comment]
Thanks @allaway ! I agree that different organization should be able to define different model release strategies. From the perspective of an architect of the new challenge platform, I can contribute by outlining the different model release strategy we (Sage) have used in the past and provide information that let the challenge organizer identify the strategy that enables their goal.

**Comment by ychae** [comment]
@allaway Would it be alright if I summarized/incorporated some of your feedback and text into the NLP-Sandbox Rules page that I'm putting together? I'll request your review so that you can check the copy before it's released.

**Comment by allaway** [comment]
Please take/paraphrase/repurpose whatever you need!

**Comment by tschaffter** [comment]
The NLP developers are free to set the sharing permission of their submissions as they wish. Incentives are given for those who release their tool under an open license (by setting a value to `Tool.license` different from `None`).
