### ISSUE TITLE
Ask governance to make the entity previewed on "Build a Tool" page completely public

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/nlpsandbox.io#51]
### Problem description

When you render an entity preview, users must be logged in to see the preview, or theres a box that says, please log in to view the entity.   See this page: https://www.synapse.org/#!Synapse:syn22277124/wiki/608483

### Possible Solution
Since this will eventually be whats on the public page, I suggest that we make this entity completely public so people don't have to be logged in to view the wiki page.

**Comment by tschaffter** [comment]
Good to know! However in this case I won't insert a preview of the OpenAPI specification because the HTML preview keeps growing and growing vertically so that it's impossible to reach the bottom of the page and stay there. This could be fixed by setting a document max height in the HTML document. I still prefer to redirect to the HTML page hosted on GitHub Pages for a full window rendering.
