### ISSUE TITLE
Add support for adding and removing pages and editing page titles using GitHub

### ISSUE THREAD

**Issue by tschaffter** [nlpsandbox/nlpsandbox.io#8]
## Background

The current workflow involved creating a Release of the repo to publish to the production site using `challengeutils mirror-wiki`. In order to have an effect, someone with write permission to the production Synapse project must create manually a structure of pages that is a subset of the structure of pages from the staging site. The command `challengeutils mirror-wiki` will then only update the pages on the production site that are present in both the production and staging site.

To summarize, the current protocol for updating the production site is:

1. Update the branch `staging`
2. Go to the production site on Synapse and create new pages (optional, only if new pages are being added by the update)
3. In this repo, create a Release to trigger `challengeutils mirror-wiki`

## Improvement

Is it possible to capture the action performed in Step 2. in this repo?

## Suggestion

@thomasyu888 What about have a `wiki_config.json` for staging and one `wiki_config.json` for production, which the file for production containing only the non-internal pages? If the command `challengeutils push-wiki` is executed to update the production site based on the production `wiki_config.json`, will the state of the production site be FULLY defined by the production `wiki_config.json` or the current state of the production site will affect the new state?

**Comment by thomasyu888** [comment]
@tschaffter It is important to pull down the state of the current production site.  The thing that you can't do is delete or move pages around with `wiki_config.json`, so you would have to `pull-wiki` if you do those things.  You can however add pages and the `id` gets filled into the new `wiki_config.json`.  I am fine with having a configuration for both staging and production (but the code doesn't allow you to specify the wiki_config name.  I could add that in so that we don't need two folders with all the markdown files.

Actually when I had a discussion about the `pull-wiki` and `push-wiki` when I fist proposed the feature for `challengeutils`, the fact that Synapse has its own markdown language makes this sort of hard to navigate.   If anyone updates any of the pages on Synapse, you will have to `pull-wiki` first, or else `push-wiki` will write over those changes.  I did also look into the potentially of looking at a "Google doc -> markdown" converter.

**Comment by tschaffter** [comment]
Related to https://sagebionetworks.jira.com/browse/PLFM-6603

**Comment by tschaffter** [comment]
This ticket is outside of the scope of this repository. Maybe this will be addressed as part of Synapse Formation, which may one day enable the deployment of wiki pages.
